name: Build and Upload as Artifact

on:
  push:
    branches:
      - master

  # Allow manually trigger
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install
        run: npm i && npm i -g lambda-build

      - name: Build
        run: npm run build

      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq archive.zip -d ./dist

      - name: Upload archive.zip as artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda_function
          path: ./dist